#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright 2013-2014 Nathanaël Jourdane
# This file is part of Zazouck.
# Zazouck is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# Zazouck is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Zazouck. If not, see <http://www.gnu.org/licenses/>.

from os import path as op
import xml.etree.ElementTree as ET
import os, subprocess, shlex, distutils.core
import process, utils

class Doc:
	def __init__(self, xml_path, zazouck_dir, doc_dir, scad_dir, jobs, openscad_path, verbose):
		self.doc_dir = doc_dir
		self.jobs = jobs
		self.openscad_path = openscad_path
		self.verbose = verbose
		self.scad_dir = scad_dir
		self.root = ET.parse(xml_path).getroot()

		doc_files_dir = op.join(zazouck_dir, 'doc_generation')
		distutils.dir_util.copy_tree(doc_files_dir, doc_dir)

		os.makedirs(op.join(self.doc_dir, 'parts_html'))
		self.make_pictures()
		#self.make_html_parts()
		#self.make_html_families()
		self.make_html_menu()
		#self.make_html_model()
		self.make_html_details(self.root)
		self.replace_html_index()

	def replace_html_index(self):
		import time
		index = op.join(self.doc_dir, 'index.html')
		os.rename(index, index + '~')

		#with open(index, 'w') as f:
		with open(index, 'w') as fout, open(index + '~', 'r') as fin:
			for line in fin:
				line = line.replace('__TITLE__', (self.root.get('id') + ' documentation').capitalize())
				line = line.replace('__MODEL_PATH__', './parts_html/' + self.root.get('id'))
				line = line.replace('__TIME__', time.strftime('on %b %d, %Y at %l:%M%p'))
				fout.write(line)

		os.remove(index + '~')

	# TODO: récursivité
	def make_html_menu(self):
		parts_dir = op.join(self.doc_dir, 'parts')
		content = ET.Element('summary')

		menu = ET.SubElement(content, 'div')
		menu.set('id', 'menu')

		link = ET.SubElement(menu, 'a')
		link.text = self.root.get('id').capitalize()
		link.set('class', 'focus')
		link.set('id', self.root.get('id'))
		link.set('href', './parts_html/' + self.root.get('id') + '.html')
		link.set('target', 'detail')

		ul_family = ET.SubElement(menu, 'ul')
		for family in self.root:
			li_family = ET.SubElement(ul_family, 'li')

			link = ET.SubElement(li_family, 'a')
			link.text = family.get('id').capitalize()
			link.set('href', './parts_html/' + family.get('id') + '.html')
			link.set('id', family.get('id'))
			link.set('onclick', 'document.getElementsByClassName("focus")[0].className = ""; this.className = "focus";')
			link.set('target', 'detail')

			ul_part = ET.SubElement(li_family, 'ul')
			for part in family:
				li_part = ET.SubElement(ul_part, 'li')

				link = ET.SubElement(li_part, 'a')
				link.text = part.get('id')
				link.set('id', part.get('id'))
				link.set('href', './parts_html/' + part.get('id') + '.html')
				link.set('onclick', 'document.getElementsByClassName("focus")[0].className = ""; this.className = "focus";')
				link.set('target', 'detail')

		file_path = op.join(self.doc_dir, 'menu.html')
		self.make_html(file_path, content, 'stylesheet.css')

	def make_html_details(self, tree):
		for elmt in tree:
			self.make_html_details(elmt)

		content = ET.Element('article')

		family_infos = ET.SubElement(content, 'div')
		family_infos.set('id', 'infos')

		if tree.get('img') != 'no':
			img_path = '../parts_img/' + tree.get('id') + '.png'
			img = ET.SubElement(family_infos, 'img')
			img.set('class', 'large')
			img.set('src', img_path)

		element_text = ET.SubElement(family_infos, 'div')
		element_text.set('id', 'text')

		# TODO: afficher nom de famille avant l'id

		ET.SubElement(element_text, 'h2').text = tree.get('id').capitalize()
		if len(tree) != 0:
			ET.SubElement(element_text, 'p').text = 'Number of childrens: ' + str(len(tree))

		if 'type' in tree.attrib:
			ET.SubElement(element_text, 'p').text = 'Type: ' + tree.get('type')

		if 'file' in tree.attrib:
			ET.SubElement(element_text, 'p').text = 'Generated by: ' + tree.get('file')

		if 'light_file' in tree.attrib:
			ET.SubElement(element_text, 'p').text = 'Light version: ' + tree.get('light_file')

		if 'data' in tree.attrib: #*
			ET.SubElement(element_text, 'p').text = 'Datas:'
			ul_data = ET.SubElement(element_text, 'ul')
			for data in tree.get('data').split(';'):
				ET.SubElement(ul_data, 'li').text = data

		if len(tree) != 0:
			ET.SubElement(content, 'hr')
			childrens = ET.SubElement(content, 'div')
			childrens.set('class', 'elements')

			ET.SubElement(childrens, 'h3').text = 'Childrens'

			for element in tree:
				childrens.append(self.html_elements(element.get('id')))

			clear_div = ET.SubElement(content, 'div')
			clear_div.set('class', 'separator')

		if 'connections' in tree.attrib:
			ET.SubElement(content, 'hr')
			connections = ET.SubElement(content, 'div')
			connections.set('class', 'elements')

			ET.SubElement(connections, 'h3').text = 'Connected to'

			for connection_id in tree.get('connections').split(';'):
				connections.append(self.html_elements(connection_id))

			clear_div = ET.SubElement(content, 'div')
			clear_div.set('class', 'separator')

		file_path = op.join(self.doc_dir, 'parts_html', tree.get('id') + '.html')
		self.make_html(file_path, content, '../stylesheet.css')

	def html_elements(self, elmt_id):
		file_path = elmt_id + '.html'

		elmt = ET.Element('a')
		#link.set('onclick', 'menu.getElementsById(' + element.get('id') + ') = "focus";')
		elmt.set('href', file_path)
		elmt.set('class', 'element')

		part_div = ET.SubElement(elmt, 'div')
		part_div.set('class', 'icon')
		ET.SubElement(part_div, 'h3').text = elmt_id.capitalize()

		img_path = '../parts_img/' + elmt_id + '.png'
		img = ET.SubElement(part_div, 'img')
		img.set('class', 'thumbnail')
		img.set('src', img_path)

		return elmt
#*
#TODO: fonction qui récupère la valeur de l'attribut un element en fonction de son id (recherche dans l'element et dans la famille)

	def make_html(self, file_path, content, css_path):
		html = ET.Element('html')
		head = ET.SubElement(html, 'head')

		link = ET.SubElement(head, 'link')
		link.set('rel', 'stylesheet')
		link.set('href', css_path)

		body = ET.SubElement(html, 'body')
		#body.set('onload', 'menu.getElementsById(' + element.get('id') + ') = "focus";')
		body.append(content)
		utils.indent(html)

		with open(file_path, 'w') as f:
			f.write('<!DOCTYPE html>\n')
			ET.ElementTree(html).write(f, 'utf-8')

	def make_pictures(self):
		IMG_SIZE = 200

		print "\n*** Creating pictures ***"

		img_dir = op.join(self.doc_dir, 'parts_img')
		os.makedirs(img_dir)

		img_opt = "--imgsize=" + str(IMG_SIZE * 2) + "," + str(IMG_SIZE * 2) + " --camera=0,0,0,45,0,45,140"

		for family in (family for family in self.root if family.get('img') != 'no'):
			part_scad_path = op.join(self.scad_dir, family.get('file'))

			process.Process(part_scad_path, family, img_dir, self.jobs, self.openscad_path, self.verbose, img_opt)

			dimentions = str(IMG_SIZE) + 'x' + str(IMG_SIZE)
			# - colorspace xxx
			process_image = 'mogrify -trim +repage -resize ' + dimentions + \
					' -background "#FFFFE5" ' + '-gravity center -extent ' + dimentions + \
					' -fuzz 10% -transparent "#FFFFE5" ' + op.join(img_dir, "*.png")
			try:
				subprocess.Popen(shlex.split(process_image))
			except:
				print "Warning: please install ImageMagic to build nice pictures for the documentation."