#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright 2013-2014 Nathanaël Jourdane
# This file is part of Zazouck.
# Zazouck is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
# Zazouck is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Zazouck. If not, see <http://www.gnu.org/licenses/>.

from os import path as op
import xml.etree.ElementTree as ET
import os, subprocess, shlex, shutil
import process, utils

class Doc:
	def __init__(self, xml_path, zazouck_dir, doc_dir, scad_dir, jobs, openscad_path, verbose):
		self.doc_dir = doc_dir
		os.makedirs(doc_dir)
		self.jobs = jobs
		self.openscad_path = openscad_path
		self.verbose = verbose
		self.scad_dir = scad_dir
		self.root = ET.parse(xml_path).getroot()

		self.make_pictures()
		self.make_part_files()
		shutil.copy(op.join(zazouck_dir, op.join("doc_generation", "doc.css")), doc_dir)
		self.create_main_file()

	def create_main_file(self):
		content = ET.Element('div')
		content.set('id', 'content')
		img_dir = op.join(self.doc_dir, 'img')

		for set in self.root:
			set_div = ET.SubElement(content, 'div')
			set_div.set('class', 'set')
			ET.SubElement(set_div, 'h2').text = set.get('name').capitalize() + 's'

			clear_div = ET.SubElement(content, 'div')
			clear_div.set('class', 'separator')

			for part in set:
				file_path = op.join(op.join(self.doc_dir, 'parts'), part.get('id') + '.html')

				part_link = ET.SubElement(set_div, 'a')
				part_link.set('href', file_path)
				part_link.set('class', 'part')

				part_div = ET.SubElement(part_link, 'div')
				part_div.set('class', 'icon')
				ET.SubElement(part_div, 'h3').text = part.get('id')

				if set.get('img') == 'true':
					img = ET.SubElement(part_div, 'img')
					img.set('class', 'thumbnail')
					img.set('src', op.join(img_dir, part.get('id') + '.png'))

		file_path = op.join(self.doc_dir, 'index.html')
		self.make_html(file_path, self.root.get('name') + " documentation", content)

	def make_part_files(self):
		parts_dir = op.join(self.doc_dir, 'parts')
		img_dir = op.join(self.doc_dir, 'img')

		os.makedirs(parts_dir)

		for set in self.root:
			type = set.get('type')
			
			for part in set:
				content = ET.Element("div")
				content.set('id', 'content')

				if set.get('img') == 'true':
					img = ET.SubElement(content, 'img')
					img.set('class', 'large')
					img.set('src', op.join(img_dir, part.get('id') + '.png'))

				file_path = op.join(parts_dir, part.get('id') + '.html')
				self.make_html(file_path, type + ' ' + part.get('id'), content)

	def make_html(self, file_path, title, content):
		CSS_FILE = op.join(self.doc_dir, 'doc.css')
		LINK = "https://github.com/roipoussiere/Zazouck"

		html = ET.Element('html')
		head = ET.SubElement(html, 'head')
		ET.SubElement(head, 'title').text = title.capitalize()

		link = ET.SubElement(head, 'link')
		link.set('rel', 'stylesheet')
		link.set('href', CSS_FILE)
		
		body = ET.SubElement(html, 'body')
		header = ET.SubElement(body, 'div')
		header.set('id', 'header')
		ET.SubElement(header, 'h1').text = title.capitalize()

		body.append(content)
		footer = ET.SubElement(body, 'div')
		footer.set('id', 'footer')
		
		# ET.SubElement(footer, 'p').text = 'Generated by <a href="' + LINK + '">Zazouck</a>'
		ET.SubElement(footer, 'p').text = 'Generated by Zazouck - www.zazouck.org'

		utils.indent(html)
		tree = ET.ElementTree(html)
		tree.write(file_path, encoding = 'UTF-8', xml_declaration = True)

	def make_pictures(self):
		IMG_SIZE = 200

		print "\n*** Creating pictures ***"

		img_dir = op.join(self.doc_dir, "img")
		if not os.path.exists(img_dir):
			os.makedirs(img_dir)

		extra_options = "--imgsize=" + str(IMG_SIZE * 2) + "," + str(IMG_SIZE * 2) + \
				" --camera=0,0,0,45,0,45,140"

		corner = self.root.find('set')
		while corner.get('img') != "true":
			corner = self.root.find('set')

		part_scad_name = corner.get('file')
		part_scad_path = op.join(self.scad_dir, part_scad_name)

		#TODO: ne pas transmettre l'arbre puisque on l'a dans self
		process.Process(part_scad_path, corner, img_dir, self.jobs, self.openscad_path, self.verbose, is_img = True)
					#part_scad_path, set_tree, export_dir, nb_job_slots, openscad_path, verbose_lvl, is_img = False, is_assembly = False
		dimentions = str(IMG_SIZE) + 'x' + str(IMG_SIZE)
		process_image = 'mogrify -trim +repage -resize ' + dimentions + \
				' -background "#FFFFE5" ' + '-gravity center -extent ' + dimentions + \
				' -fuzz 5% -transparent "#FFFFE5" ' + op.join(img_dir, "*.png")
		try:
			subprocess.Popen(shlex.split(process_image))
		except:
			print "Please install ImageMagic to build nice pictures for the documentation."
